#!/bin/bash
# Runs one or more tests for files
# Argument is a specific test file (w/o extension) or none.

SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >>/dev/null && pwd )"
cd $SOURCE
echo $SOURCE
#cd $HOME/SciSheets/mysite/scisheets/core

function runTests {
for f in $@
do
  echo ""
  echo "** $f **"
  dt.sh ${f}
  #read -p "Press [Enter] to continue ..."
done
}


# Main code
if [ $# -eq 0 ]; then
  file_list=`ls test_*.py | grep -v generated`
  runTests $file_list
  cd helpers
  runTests `ls test_*.py `
else
  runTests $1
fi
