#!/bin/bash
# Runs one or more tests for files
# Argument is a specific test file (w/o extension) or none.

TEST_LIST="test_api test_table_evaluator test_column test_table"
TEST_LIST="${TEST_LIST} util.test_combinatoric_lists util.test_trinary"
TEST_LIST="${TEST_LIST} util.test_util"

function runTests {
for f in $@
do
  echo ""
  echo "** $f **"
  dt.sh ${f}
done
}


# Main code

FILE_PATH="scisheets.core."

if [ $# -eq 0 ]; then
  runTests ${TEST_LIST}
else
  runTests $1
fi
