#!/bin/bash
# Prepares the test file and run the tests.

#SITE=$HOME/Documents/SciSheets/mysite/mysite
SITE=$(dirname $(dirname $PWD))
cp $SITE/templates/scitable.html test1.html
sed 's/.{% static "/"..\//' <test1.html >test2.html
sed 's/ %}.//' <test2.html >test3.html
sed '/scisheets.js/r insert_mock.html' < test3.html > test4.html
sed '/sheet_setup.js/r insert.html' < test4.html > test5.html
sed '/load static from/s/^.*$//' < test5.html > test6.html
sed '/include "scitable_data.html/s/^.*$//' < test6.html > test.html
mv test?.html /tmp
#echo "****Running tests in batch may cause some to fail. Continue?"
#echo "    Consider opening test.html in a browser."
#read dummy
bash qunit.sh test.html
